version: 0.0
os: linux
files:
  - source: /index.html
    destination: /home/ec2-user/code-deploy-node/
hooks:
  BeforeInstall:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: root

